application: my-app
version: 1
runtime: python
api_version: 1

handlers:
- url: /(robots\.txt|favicon\.ico)
  static_files: static/\1
  upload: static/(.*)

- url: /js/(.*\.js)
  static_files: static/js/\1
  upload: static/js/(.*\.js)

- url: /css/(.*\.css)
  static_files: static/css/\1
  upload: static/css/(.*\.css)

- url: /images/(.*\.(png|jpg))
  static_files: static/images/\1
  upload: static/images/(.*\.(png|jpg))

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /_ah/queue/deferred
  script: main.py
  login: admin

- url: /.*
  script: main.py
